services:
  immo-vendee:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      CONFIG_PATH: /app/config.yml
      DB_PATH: /app/data/annonces.sqlite
      OUTPUT_PATH: /app/output/rapport.html
      IMAP_HOST: ${IMAP_HOST}
      IMAP_PORT: ${IMAP_PORT}
      IMAP_USER: ${IMAP_USER}
      IMAP_PASSWORD: ${IMAP_PASSWORD}
      IMAP_FOLDER: ${IMAP_FOLDER}
      MARK_EMAILS_AS_SEEN: ${MARK_EMAILS_AS_SEEN}
    volumes:
      - /docker/data/immo-vendee/data:/app/data
      - /docker/data/immo-vendee/output:/app/output
      - /docker/data/immo-vendee/config.yml:/app/config.yml:ro
    restart: "no"

  immo-vendee-web:
    image: nginx:alpine
    container_name: immo-vendee-web
    ports:
      - "8088:80"
    volumes:
      - /docker/data/immo-vendee/output:/usr/share/nginx/html:ro
    restart: unless-stopped
